/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_de_stagiaires;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class JFrame extends javax.swing.JFrame {

    private DefaultTableModel dt;
    private int id;
    private String nom, prenom, sexe, service, duree;
    private int i; //indice de deplacement
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtDuree = new javax.swing.JTextField();
        combService = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jrb1 = new javax.swing.JCheckBox();
        jrb2 = new javax.swing.JCheckBox();
        btnSuivant = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStg = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        combRecherche = new javax.swing.JComboBox<>();
        txtRecherche = new javax.swing.JTextField();
        Btn5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prénom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Service :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Durée :");

        txtNom.setBackground(new java.awt.Color(245, 245, 245));
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtPrenom.setBackground(new java.awt.Color(245, 245, 245));
        txtPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomActionPerformed(evt);
            }
        });

        txtId.setBackground(new java.awt.Color(245, 245, 245));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtDuree.setBackground(new java.awt.Color(245, 245, 245));
        txtDuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDureeActionPerformed(evt);
            }
        });

        combService.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        combService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatique", "Logistique", "RH", "Management" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sexe :");

        jrb1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrb1.setText("Homme");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });

        jrb2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrb2.setText("Femme");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });

        btnSuivant.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnPrecedent.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrecedent.setText("Précédent");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        Btn1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Gestion_des_stagiaires\\icons\\plus.png")); // NOI18N
        Btn1.setText("Ajouter");
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn1MouseEntered(evt);
            }
        });
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(255, 255, 255));
        Btn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Gestion_des_stagiaires\\icons\\shuffle.png")); // NOI18N
        Btn2.setText("Modifier");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setBackground(new java.awt.Color(255, 255, 255));
        Btn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Gestion_des_stagiaires\\icons\\remove.png")); // NOI18N
        Btn3.setText("Supprimer");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn4.setBackground(new java.awt.Color(255, 255, 255));
        Btn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Gestion_des_stagiaires\\icons\\loading.png")); // NOI18N
        Btn4.setText("Actualiser");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        tableStg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStg.setMaximumSize(new java.awt.Dimension(829, 540));
        tableStg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStg);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rechercher par:");

        combRecherche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combRecherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nom", "Service" }));

        txtRecherche.setBackground(new java.awt.Color(245, 245, 245));
        txtRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheActionPerformed(evt);
            }
        });

        Btn5.setBackground(new java.awt.Color(255, 255, 255));
        Btn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Gestion_des_stagiaires\\icons\\search.png")); // NOI18N
        Btn5.setText("Rechercher");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        jLabel8.setText("By SALHAOUI Mohamed");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Application de Gestion des stagiaires");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrecedent))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrb1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addComponent(txtDuree)
                            .addComponent(txtPrenom)
                            .addComponent(txtNom)
                            .addComponent(txtId)
                            .addComponent(combService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)))
                        .addComponent(Btn5)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jrb1)
                            .addComponent(jrb2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuivant)
                            .addComponent(btnPrecedent)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtDureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDureeActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        sexe = jrb1.getText();
    }//GEN-LAST:event_jrb1ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        sexe = jrb2.getText();
    }//GEN-LAST:event_jrb2ActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        try{
            i++;
            Deplacer(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de deplacement !\n"+e.getMessage());
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        try{
            i--;
            Deplacer(i);
        // ou DeplacerStagiaire(--i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de deplacement !\n"+e.getMessage());
        }
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void txtRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheActionPerformed

    private void Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseEntered

    }//GEN-LAST:event_Btn1MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            //Connection avec DB
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stg1 ?useUnicode=true &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false& serverTimezone=UTC","root","");
            st = con.createStatement();
            
            jrbg.add(jrb1);
            jrbg.add(jrb2);
            
            dt = new DefaultTableModel();//Pour stocker les elements d'un tableau
            
            dt.addColumn("id");
            dt.addColumn("nom");
            dt.addColumn("prenom");
            dt.addColumn("service");
            dt.addColumn("duree");
            dt.addColumn("sexe");
           
            tableStg.setModel(dt);
            
            Afficher();
            i=0;
            Deplacer(i);
           
            
        }catch(Exception e){
            System.out.printf("error: "+e.getMessage());
            JOptionPane.showMessageDialog(null, "Erreur de connexion\n "+e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void tableStgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStgMouseClicked
         try{
        i = tableStg.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur
         
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de selection de stagiaire\n"+e.getMessage());
    }
    }//GEN-LAST:event_tableStgMouseClicked

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        try{
   
            String sql = "INSERT INTO stagiaire  (nom,prenom,service,duree_de_stage,sexe)VALUES (?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtNom.getText());
            ps.setString(2, txtPrenom.getText());
            ps.setString(3, combService.getSelectedItem().toString());
            ps.setString(4, txtDuree.getText());
            ps.setString(5, sexe);
    
      
            ps.executeUpdate();
            Afficher(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "Stagiaire est ajouté avec succes");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur d'ajout stg\n"+e.getMessage());
            System.err.println(""+e.getMessage());
        }
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        try{ 
        // msg d confirmation !
        txtId.setEnabled(true);
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","Alerte Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE stagiaire SET id='"+txtId.getText()+"',nom='"+txtNom.getText()
      +"',prenom='"+txtPrenom.getText()+"',service='"+combService.getSelectedItem().toString()
                   +"',duree_de_stage='"+txtDuree.getText()+"',sexe='"+sexe
                   +"' WHERE id = "+ txtId.getText());       
           //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
           Afficher(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        try{
        if(JOptionPane.showConfirmDialog(null, "Supprimer le stagiaire!","Alerte Suppression",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION){
                st.executeUpdate("Delete from stagiaire where id = "+ txtId.getText());
                Afficher(); // recharger la liste des stagiaires ...
           
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de suppression !\n"+e.getMessage());
    }
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        actualiser();
        Afficher();
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        try { 
            dt.setRowCount(0); //pour vider tableau 
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery( "SELECT * FROM stagiaire WHERE "+combo()
                +"  like '%"+txtRecherche.getText()+"%'" );
    
            while(rs.next()){
                id=rs.getInt(1); 
                nom = rs.getString(2);
                prenom = rs.getString(3);
                service = rs.getString(4);
                duree=rs.getString(5);
                sexe=rs.getString(6);
            
                Object[] stg = {id,nom,prenom,service,duree,sexe};
                dt.addRow(stg);
            }
     
            if (dt.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
                Afficher(); // afficehr tout les stgs
            }else if(i==0){
                Deplacer(i);
            }
    
        }catch (Exception m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
            System.err.println(m);
        }
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Afficher(){
        txtId.setEnabled(false);
        try{
            dt.setRowCount(0); //Vider la liste des stagiaires
            rs = st.executeQuery("Select * from stagiaire");
            
            while(rs.next()){
                id=rs.getInt("id");
                nom=rs.getString("nom");
                prenom=rs.getString("prenom");
                service=rs.getString("service");
                duree=rs.getString("duree_de_stage");
                sexe=rs.getString("sexe");
                
                Object[] stg = {id, nom, prenom, service, duree, sexe};
                dt.addRow(stg);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur d'affichage de la liste des stagiaires \n "+e.getMessage());
        }
    }
    
    private void Deplacer(int i){
        try{
            if (dt.getRowCount() == 0){ //si il y aucun enregistrement tableau est vide
            btnPrecedent.setEnabled(false);
            btnSuivant.setEnabled(false);
            actualiser();
            }else{
            if(i == 0){ //si i est localiser sur le premier enregistrement  
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(true);
            }else if (i == dt.getRowCount()-1){ //  si i est localisé sur  dernier enregistrement
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(false);
            }else{
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(true);
            }
            if(dt.getRowCount() == 1){//si il y a un seul enregistrement, nous avons un seul ligne
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(false);
            }
            }
            txtId.setText(dt.getValueAt(i, 0).toString()); 
            txtNom.setText(dt.getValueAt(i, 1).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
            txtPrenom.setText(dt.getValueAt(i, 2).toString());
            combService.setSelectedItem(dt.getValueAt(i, 3).toString());
            txtDuree.setText(dt.getValueAt(i, 4).toString());
            String s = dt.getValueAt(i, 5).toString();
            if(s.equals("Homme")){jrb1.setSelected(true);}else if(s.equals("Femme")){jrb2.setSelected(true);}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
        }
    }
    
    public void actualiser(){ // fonction de type void ne retourne rien !!!!!!??
        txtId.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        combService.setSelectedItem(1);
        jrb1.isSelected();
        txtDuree.setText("");
    }
    
    String combo(){
        switch(combRecherche.getSelectedIndex()){ 
            case 0: return "id"; 
            case 1: return "nom";
            case 2: return "service";
        }
        return "";
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JComboBox<String> combRecherche;
    private javax.swing.JComboBox<String> combService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jrb1;
    private javax.swing.JCheckBox jrb2;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JTable tableStg;
    private javax.swing.JTextField txtDuree;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
